from __future__ import annotations

import os
import sys
from datetime import datetime

# 动态将青龙 scripts 根目录加入模块搜索路径，兼容将脚本放在子目录执行的场景
_ql_scripts_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if _ql_scripts_dir not in sys.path:
    sys.path.append(_ql_scripts_dir)

from wxpusher_utils import (
    PanelExtra,
    PanelItem,
    PanelMetric,
    PanelTag,
    PanelTask,
    push_html_panel,
)


def collect_results() -> list[dict]:
    # Replace this mock data with real business logic.
    return [
        {
            "name": "账号1",
            "status": "success",
            "value": "+12",
            "desc": "任务全部完成",
            "meta": "当前积分 348",
            "tasks": [
                {"title": "签到", "status": "success", "detail": "已完成", "value": "+2"},
                {"title": "浏览", "status": "success", "detail": "已完成", "value": "+10"},
            ],
            "extras": [
                {"label": "连续天数", "value": "7", "tone": "primary"},
                {"label": "余额", "value": "348", "tone": "success"},
            ],
            "tags": [
                {"text": "全部完成", "tone": "success"},
            ],
            "lines": [
                "账号状态正常",
            ],
        },
        {
            "name": "账号2",
            "status": "warning",
            "value": "待登录",
            "desc": "Cookie 失效，本次已跳过后续任务",
            "meta": "需要重新抓包",
            "tasks": [
                {"title": "签到", "status": "danger", "detail": "Cookie 失效", "value": "fail"},
            ],
            "extras": [
                {"label": "当前积分", "value": "120", "tone": "neutral"},
            ],
            "tags": [
                {"text": "Cookie 失效", "tone": "warning"},
            ],
            "lines": [
                "未继续执行后续任务",
                "避免无意义重试",
            ],
        },
    ]


def build_push_payload(results: list[dict]) -> tuple[str, list[PanelMetric], list[PanelItem]]:
    success_count = sum(1 for item in results if item["status"] == "success")
    warning_count = sum(1 for item in results if item["status"] == "warning")
    fail_count = sum(1 for item in results if item["status"] == "danger")

    summary = f"任务完成 {success_count} 正常 / {warning_count} 待处理 / {fail_count} 异常"
    metrics = [
        PanelMetric("总账号", str(len(results)), "primary"),
        PanelMetric("正常", str(success_count), "success"),
        PanelMetric("待处理", str(warning_count), "warning"),
        PanelMetric("异常", str(fail_count), "danger"),
    ]
    items = [
        PanelItem(
            title=item["name"],
            value=item.get("value", ""),
            desc=item.get("desc", ""),
            meta=item.get("meta", ""),
            status=item["status"],
            tasks=[PanelTask(**task) for task in item.get("tasks", [])],
            extras=[PanelExtra(**extra) for extra in item.get("extras", [])],
            tags=[PanelTag(**tag) for tag in item.get("tags", [])],
            lines=item.get("lines", []),
        )
        for item in results
    ]
    return summary, metrics, items


def main() -> None:
    results = collect_results()
    summary, metrics, items = build_push_payload(results)
    ok, data, _ = push_html_panel(
        summary=summary,
        title="脚本执行报告",
        subtitle=datetime.now().strftime("%Y-%m-%d %H:%M"),
        metrics=metrics,
        items=items,
        footer="Generated by WXPUSHER_TEMPLATE.py",
        theme="auto",
    )
    print("push_ok =", ok)
    print("push_data =", data)


if __name__ == "__main__":
    main()
